add channel-pruning MIT license
quic/aimet pull request #2065
Opened 2023-04-01 18:26 UTC by yihui-he

Hi, thanks for the awesome work and for implementing Channel Pruning.

I'm the first author of the Channel Pruning paper (Channel Pruning for Accelerating Very Deep Neural Networks)

As my project is licensed under the MIT License, I have created this pull request to ensure compliance with the license terms.

In this PR,
- I have Included attribution comments at the top of the relevant source files that use or modify code from my project.
- Updated the doc to mention the original technical paper.

Thank you for your attention to this matter!

2023-04-03 20:30 UTC, quic-mangal commented
@yihui-he, thanks for pointing this out and adding the relevant license.

2023-04-03 20:47 UTC, quic-bharathr approved these changes

2023-04-03 21:00 UTC, quic-bharathr requested changes
Needs discussion

2023-04-18 20:37 UTC, yihui-he commented
Hi @quic-mangal @quic-akhobare @quic-bharathr Thanks for your attention to this matter. 
May I request a testimonial letter from QuIC or you attesting to the fact that QuIC implemented my work in AIMET? The letter is for a USCIS officer to read and for green card application purposes. My attorney can provide a draft letter.

I understand that QuIC is a busy organization, and I appreciate any time that you can spare to provide this letter. The purpose of this testimonial is to support my immigration application, which requires evidence of my contributions to the field of technology.

Although there's already evidence channel pruning is implemented here, it would be too technical for the USCIS officer. The best evidence is to obtain a letter.

If you require any additional information or documentation, please do not hesitate to let me know. 

my email: he@yihui.dev
linkedin: https://www.linkedin.com/in/heyihui/

2026-03-16 21:21 UTC, quic-akhobare commented
After giving it careful consideration, we decided to not accept this PR. AIMET code continues to be open sourced with a permissive 3-clause BSD license.

If you have further questions, feel free to join our[ Slack Community ](http://aihub.qualcomm.com/community/slack) specifically the #aimet channel to discuss easily!

2026-03-16 21:21 UTC, closed without merging